# Generated by Django 5.1.4 on 2025-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('seller_name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_price', models.TextField(blank=True, null=True)),
                ('final_price', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('reviews_count', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('asin', models.TextField(blank=True, null=True)),
                ('buybox_seller', models.TextField(blank=True, null=True)),
                ('number_of_sellers', models.TextField(blank=True, null=True)),
                ('root_bs_rank', models.TextField(blank=True, null=True)),
                ('answered_questions', models.TextField(blank=True, null=True)),
                ('domain', models.TextField(blank=True, null=True)),
                ('images_count', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('video_count', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('item_weight', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('product_dimensions', models.TextField(blank=True, null=True)),
                ('seller_id', models.TextField(blank=True, null=True)),
                ('date_first_available', models.TextField(blank=True, null=True)),
                ('discount', models.TextField(blank=True, null=True)),
                ('model_number', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('plus_content', models.TextField(blank=True, null=True)),
                ('upc', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('top_review', models.TextField(blank=True, null=True)),
                ('variations', models.TextField(blank=True, null=True)),
                ('delivery', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('buybox_prices', models.TextField(blank=True, null=True)),
                ('parent_asin', models.TextField(blank=True, null=True)),
                ('input_asin', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('origin_url', models.TextField(blank=True, null=True)),
                ('bought_past_month', models.TextField(blank=True, null=True)),
                ('is_available', models.TextField(blank=True, null=True)),
                ('root_bs_category', models.TextField(blank=True, null=True)),
                ('bs_category', models.TextField(blank=True, null=True)),
                ('bs_rank', models.TextField(blank=True, null=True)),
                ('badge', models.TextField(blank=True, null=True)),
                ('subcategory_rank', models.TextField(blank=True, null=True)),
                ('amazon_choice', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('product_details', models.TextField(blank=True, null=True)),
                ('prices_breakdown', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.TextField(blank=True, null=True)),
                ('from_the_brand', models.TextField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('seller_url', models.TextField(blank=True, null=True)),
                ('customer_says', models.TextField(blank=True, null=True)),
                ('sustainability_features', models.TextField(blank=True, null=True)),
                ('climate_pledge_friendly', models.TextField(blank=True, null=True)),
                ('videos', models.TextField(blank=True, null=True)),
                ('other_sellers_prices', models.TextField(blank=True, null=True)),
                ('downloadable_videos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_data',
                'managed': False,
            },
        ),
    ]
