# Generated by Django 5.1.5 on 2025-01-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_productdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
