# Generated by Django 5.1.5 on 2025-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_productdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
