# Generated by Django 5.1.5 on 2025-01-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_productdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
